export enum NotificationType {
    INFO = 'INFO',
    ISIN_SERIES_CONFLICT = 'ISIN_SERIES_CONFLICT',
    DATA_INGESTION_FAILED = 'DATA_INGESTION_FAILED',
    DATA_INGESTION_SUCCESS = 'DATA_INGESTION_SUCCESS',
    OTP = 'OTP',
}